### ISSUE TITLE
SPIFFS is (slowly) being supersceeded by LittleFS in the Expressif core

### ISSUE THREAD

**Issue by easytarget** [lucadentella/SPIFFS_ImageReader#1]
Just a comment really, 
https://docs.platformio.org/en/latest/platforms/espressif8266.html#selecting-appropriate-filesystem
you may want to consider extending this to LittleFS,
PS: Handy library, just what I needed to jazz up something I'm working on with pictures :-)

**Comment by lucadentella** [comment]
Hi Owen,

thanks for your comment! To be honest I only tested the library with esp32 and SPIFFS seemed the most straightforward option, considering also the "data upload plugin" for Arduino IDE which makes uploading images to that partition super easy.

I'll give a look also to LittleFS implementation and, why not, include it in my library as well.

**Comment by lucadentella** [comment]
In addition, it seems that espressif position on SPIFFS is slightly different from the one of the community behind 8266 core, as mentioned here espressif/arduino-esp32#3765

**Comment by easytarget** [comment]
Yes, I'd noticed that. I just came to this because I was using this library, but I keep updated to other esp32 based projects, and one of them just switched to LittleFS. So it was in my mind and I thought I'd mention it. I dont think SPIFFS is going away soon. 
PS: I hadn't spotted that plugin; looks handy :-)

**Comment by lucadentella** [comment]
Thanks, closing the issue for now... I'll evaluate the possibility to add LittleFS support in the next major release
