### ISSUE TITLE
Working With Bitluni's ESP32Lib VGA

### ISSUE THREAD

**Issue by e-labInnovations** [lucadentella/SPIFFS_ImageReader#3]
Bitluni's ESP32Lib VGA works with Adafruit GFX. But I can't use this library with it
Please give support
[ESP32Lib](https://github.com/bitluni/ESP32Lib/)
[https://github.com/bitluni/ESP32Lib/issues/65](https://github.com/bitluni/ESP32Lib/issues/65)

**Comment by lucadentella** [comment]
Hi! I cannot test the VGA library, which error do you receive?

**Comment by lucadentella** [comment]
better continue in the "original" issue (ESP32Lib/issues/65)
